In [1]:
import numpy as np

## Creating ndarrays


In [2]:
arr = np.arange(10)


In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[4]

4

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr_slice = arr[5:8]

In [9]:
arr_slice

array([12, 12, 12])

In [10]:
arr_slice[0] = 12345

In [11]:
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [12]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

In [13]:
arr2d[2]

array([7, 8, 9])

In [14]:
arr2d[2,2]

9

In [15]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [16]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr3d[0]


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
old_values = arr3d[0].copy()

In [19]:
arr3d[0] = 43

In [20]:
arr3d

array([[[43, 43, 43],
        [43, 43, 43]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
arr3d[0] = old_values

In [22]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[1]


array([[ 7,  8,  9],
       [10, 11, 12]])

## index with slicing 

In [24]:
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [25]:
arr[1:6]

array([    1,     2,     3,     4, 12345])

In [26]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[:2] # selecting two rows

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr2d[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2d[1, :2] # select second row and the first two columns

array([4, 5])

In [31]:
arr2d[:2, 2] # Third column but only first two rows

array([3, 6])

In [32]:
arr2d[:, :1] # selecting the entire axis through the colon

array([[1],
       [4],
       [7]])

In [33]:
arr2d[1, :]

array([4, 5, 6])

In [34]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [35]:
arr2d[1, 1]

5

In [36]:
arr2d[1, :3]

array([4, 5, 6])

In [37]:
arr2d[:2, 1:] = 0

In [38]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [39]:
arr2d.shape

(3, 3)

In [40]:
arr2d[:2, ] = 0

In [41]:
arr2d

array([[0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

# Boolean Indexing

In [42]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [43]:
data = np.random.randn(7, 4)

In [44]:
data

array([[-0.32570732, -1.6166031 ,  1.61634637,  0.54246886],
       [ 0.8510554 ,  0.93875616, -1.49845397,  1.50273531],
       [-1.29881188, -0.07470567, -1.09164549, -0.07532317],
       [-1.05878285,  0.33850456,  0.50947263,  0.10404379],
       [ 0.51144801, -0.68313156, -0.82814034, -0.79275602],
       [ 0.03578283, -0.20761868,  0.64270256, -0.05747425],
       [-0.70458243,  1.11353965, -0.89560449, -1.48269102]])

In [45]:
data.shape

(7, 4)

In [46]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [47]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [48]:
data[names == 'Bob']

array([[-0.32570732, -1.6166031 ,  1.61634637,  0.54246886],
       [-1.05878285,  0.33850456,  0.50947263,  0.10404379]])

In [49]:
data[names == 'Bob', 2:]

array([[1.61634637, 0.54246886],
       [0.50947263, 0.10404379]])

In [50]:
data


array([[-0.32570732, -1.6166031 ,  1.61634637,  0.54246886],
       [ 0.8510554 ,  0.93875616, -1.49845397,  1.50273531],
       [-1.29881188, -0.07470567, -1.09164549, -0.07532317],
       [-1.05878285,  0.33850456,  0.50947263,  0.10404379],
       [ 0.51144801, -0.68313156, -0.82814034, -0.79275602],
       [ 0.03578283, -0.20761868,  0.64270256, -0.05747425],
       [-0.70458243,  1.11353965, -0.89560449, -1.48269102]])

In [51]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [52]:
mask = (names == 'Bob') | (names == 'will')

In [53]:
mask

array([ True, False, False,  True, False, False, False])

In [54]:
data[mask]

array([[-0.32570732, -1.6166031 ,  1.61634637,  0.54246886],
       [-1.05878285,  0.33850456,  0.50947263,  0.10404379]])

In [55]:
data

array([[-0.32570732, -1.6166031 ,  1.61634637,  0.54246886],
       [ 0.8510554 ,  0.93875616, -1.49845397,  1.50273531],
       [-1.29881188, -0.07470567, -1.09164549, -0.07532317],
       [-1.05878285,  0.33850456,  0.50947263,  0.10404379],
       [ 0.51144801, -0.68313156, -0.82814034, -0.79275602],
       [ 0.03578283, -0.20761868,  0.64270256, -0.05747425],
       [-0.70458243,  1.11353965, -0.89560449, -1.48269102]])

In [56]:

data[names == 'Bob']

array([[-0.32570732, -1.6166031 ,  1.61634637,  0.54246886],
       [-1.05878285,  0.33850456,  0.50947263,  0.10404379]])

In [57]:
cond = names == 'Bob'

In [58]:
data[~cond]

array([[ 0.8510554 ,  0.93875616, -1.49845397,  1.50273531],
       [-1.29881188, -0.07470567, -1.09164549, -0.07532317],
       [ 0.51144801, -0.68313156, -0.82814034, -0.79275602],
       [ 0.03578283, -0.20761868,  0.64270256, -0.05747425],
       [-0.70458243,  1.11353965, -0.89560449, -1.48269102]])

In [61]:
mask = (names == 'Bob') | (names == 'will')

In [62]:
data[mask]

array([[-0.32570732, -1.6166031 ,  1.61634637,  0.54246886],
       [-1.05878285,  0.33850456,  0.50947263,  0.10404379]])

In [63]:
data[data < 0] = 0

In [64]:
data

array([[0.        , 0.        , 1.61634637, 0.54246886],
       [0.8510554 , 0.93875616, 0.        , 1.50273531],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.33850456, 0.50947263, 0.10404379],
       [0.51144801, 0.        , 0.        , 0.        ],
       [0.03578283, 0.        , 0.64270256, 0.        ],
       [0.        , 1.11353965, 0.        , 0.        ]])

In [65]:
data[names != 'Joe'] = 7

In [66]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.8510554 , 0.93875616, 0.        , 1.50273531],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.03578283, 0.        , 0.64270256, 0.        ],
       [0.        , 1.11353965, 0.        , 0.        ]])