In [1]:
import numpy as np

## Creating ndarrays


In [2]:
arr = np.arange(10)


In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[4]

4

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr_slice = arr[5:8]

In [9]:
arr_slice

array([12, 12, 12])

In [10]:
arr_slice[0] = 12345

In [11]:
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [12]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

In [13]:
arr2d[2]

array([7, 8, 9])

In [14]:
arr2d[2,2]

9

In [15]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [16]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr3d[0]


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
old_values = arr3d[0].copy()

In [19]:
arr3d[0] = 43

In [20]:
arr3d

array([[[43, 43, 43],
        [43, 43, 43]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
arr3d[0] = old_values

In [22]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[1]


array([[ 7,  8,  9],
       [10, 11, 12]])

## index with slicing 

In [24]:
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [25]:
arr[1:6]

array([    1,     2,     3,     4, 12345])

In [26]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[:2] # selecting two rows

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr2d[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2d[1, :2] # select second row and the first two columns

array([4, 5])

In [31]:
arr2d[:2, 2] # Third column but only first two rows

array([3, 6])

In [32]:
arr2d[:, :1] # selecting the entire axis through the colon

array([[1],
       [4],
       [7]])

In [33]:
arr2d[1, :]

array([4, 5, 6])

In [34]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [35]:
arr2d[1, 1]

5

In [36]:
arr2d[1, :3]

array([4, 5, 6])

In [37]:
arr2d[:2, 1:] = 0

In [38]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [39]:
arr2d.shape

(3, 3)

In [40]:
arr2d[:2, ] = 0

In [41]:
arr2d

array([[0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

# Boolean Indexing

In [42]:
names = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Joe'])

In [43]:
data = np.random.randn(7, 4)

In [44]:
data

array([[-1.77798053e-02, -3.23062839e-01, -5.67488243e-02,
        -2.47060872e+00],
       [ 1.21880110e+00, -8.38535465e-01,  4.89475995e-01,
        -8.21801297e-01],
       [ 1.20316000e+00, -4.36858623e-01,  2.47636414e-01,
        -6.23916709e-05],
       [ 1.99396543e-01, -3.74805984e-01,  3.49915078e-01,
         2.10610136e-01],
       [ 1.60469642e+00,  6.89884230e-01, -9.10584248e-01,
         8.53334790e-01],
       [-9.16687580e-02, -9.11307088e-01, -1.18036843e+00,
        -5.85848479e-01],
       [-2.57769388e-01, -1.54899606e+00, -1.17822563e+00,
        -5.17065471e-01]])