In [28]:
import numpy as np

## Creating ndarrays


In [2]:
arr = np.arange(10)


In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[4]

4

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr_slice = arr[5:8]

In [9]:
arr_slice

array([12, 12, 12])

In [10]:
arr_slice[0] = 12345

In [11]:
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [12]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

In [15]:
arr2d[2]

array([7, 8, 9])

In [16]:
arr2d[2,2]

9

In [17]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [18]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr3d[0]


array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
old_values = arr3d[0].copy()

In [21]:
arr3d[0] = 43

In [22]:
arr3d

array([[[43, 43, 43],
        [43, 43, 43]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[0] = old_values

In [24]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[1]


array([[ 7,  8,  9],
       [10, 11, 12]])

## index with slicing 

In [29]:
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [30]:
arr[1:6]

array([    1,     2,     3,     4, 12345])

In [31]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[:2] # selecting two rows

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [37]:
arr2d[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[1, :2] # select second row and the first two columns

array([4, 5])

In [39]:
arr2d[:2, 2] # Third column but only first two rows

array([3, 6])