In [1]:
import numpy as np

In [3]:
my_arr = np.arange(1000)


In [4]:
my_list = list(range(1000))

In [20]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 80 µs, sys: 40 µs, total: 120 µs
Wall time: 97.8 µs


In [30]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 751 µs, sys: 1 µs, total: 752 µs
Wall time: 755 µs


In [31]:
data = np.random.randn(2, 3)

In [32]:
data

array([[ 1.13086923,  0.54883902, -1.49601156],
       [ 2.1268724 ,  1.83717801,  0.53200019]])

In [33]:
data * 10

array([[ 11.30869228,   5.48839019, -14.96011562],
       [ 21.26872397,  18.37178011,   5.32000189]])

# creating ndarrays

In [34]:
data = [6, 7.8, 8, 0, 1]

In [35]:
arr1 = np.array(data)

In [36]:
arr1

array([6. , 7.8, 8. , 0. , 1. ])

In [38]:
arr1.shape

(5,)

In [39]:
data2 = [[1,2,3],[2,3,5]]

In [40]:
arr2 = np.array(data2)

In [41]:
arr2

array([[1, 2, 3],
       [2, 3, 5]])

In [42]:
arr2.ndim

2

In [43]:
arr2.shape

(2, 3)

In [44]:
arr2.dtype

dtype('int64')